/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  contributing: [{type: 'autogenerated', dirName: 'contributing'}],
  installation: [{type: 'autogenerated', dirName: 'installation'}],
  protocol: [{type: 'autogenerated', dirName: 'protocol'}, "video-miners/terminology"],
  orchestrators: [{type: 'autogenerated', dirName: 'video-miners'}],
  video_devs: [{type: 'autogenerated', dirName: 'video-developers'}, "video-miners/terminology"],
  delegators: [{type: 'autogenerated', dirName: 'delegators'}, "video-miners/terminology"]
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
