blank_issues_enabled: false
contact_links:
  - name: Ask Question
    url: https://discord.com/channels/423160867534929930/1102991036080472247
    about: Ask questions and discuss with other community members
