name: Update Review Template

on:
  workflow_dispatch:

jobs:
  update-review-template:
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder
        run: |
          echo "Not yet implemented - see update-review-template.yml in backlog"
