// Single source of truth: re-exports from globals.jsx which is updated by GHA on each go-livepeer release.
// Do not edit this file manually — update globals.jsx or trigger update-livepeer-release.yml.
export { latestVersion, latestVersionUrl } from '../../automations/globals/globals.jsx';
