workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    livepeer-studio-api:
        inputs:
            - location: https://raw.githubusercontent.com/livepeer/studio/master/packages/api/src/schema/api-schema.yaml
        overlays:
            - location: https://raw.githubusercontent.com/livepeer/livepeer-js/main/codeSamples.yaml
        output: output.yaml
        registry:
            location: registry.speakeasyapi.dev/livepeer/livepeer-studio/livepeer-studio-api
targets: {}
