/**
 * Auto-generated by fetch-contract-addresses.js
 * Source: livepeer/governor-scripts (commit 2cb192a) AND ...
 * Last updated: 2026-03-26T04:46:31.137Z
 * DO NOT EDIT MANUALLY
 */

// put jsdocs style of how this data is strucutred here

export const helpTooltips = {
  name: {},
  type: { standalone: '' },
  chain: { arbitrumOne: '' },
}

export const contractAddresses = {
  arbitrumOne: {
    current: [
      {
        name: 'LivepeerToken',
        address: '0x289ba1701C2F088cf0faf8B3705246331cB8A839',
        type: 'standalone',
        category: 'token',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z', //must be human readable DD Month YYYY
        repoSrc: '',
        contractRepoUrl: '',
        chain: '',
        meta: {
          // other notes needed for pages
          //
        },
      },
      {
        name: 'BondingVotes',
        address: '0x0B9C254837E72Ebe9Fe04960C43B69782E68169A',
        type: 'proxy',
        category: 'governance',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'BondingVotes',
        address: '0x1561fC5F7Efc049476224005DFf38256dccfc509',
        type: 'target',
        category: 'governance',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'Governor',
        address: '0xD9dEd6f9959176F0A04dcf88a0d2306178A736a6',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'LivepeerGovernor',
        address: '0xd2Ce37BCB287CaDc40647f567C2D3C4220901634',
        type: 'target',
        category: 'governance',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'LivepeerGovernor',
        address: '0xcFE4E2879B786C3aa075813F0E364bb5acCb6aa0',
        type: 'proxy',
        category: 'governance',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'MerkleSnapshot',
        address: '0x10736ffaCe687658F88a46D042631d182C7757f7',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'PollCreator',
        address: '0x8bb50806D60c492c0004DAD5D9627DAA2d9732E6',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'Treasury',
        address: '0xf82C1FF415F1fCf582554fDba790E27019c8E8C4',
        type: 'standalone',
        category: 'governance',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'L2LPTDataCache',
        address: '0xd78b6bD09cd28A83cFb21aFa0DA95c685A6bb0B1',
        type: 'standalone',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'L2LPTGateway',
        address: '0x6D2457a4ad276000A615295f7A80F79E48CcD318',
        type: 'standalone',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'L2Migrator',
        address: '0x148D5b6B4df9530c7C76A810bd1Cdf69EC4c2085',
        type: 'proxy',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'L2Migrator',
        address: '0x93BB030735747708b4D33093A98d4c804Cd6B58C',
        type: 'target',
        category: 'bridge',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'SortedDoublyLL',
        address: '0xC45f6918F7Bcac7aBc8fe05302b3cDF39776cdeb',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'AIServiceRegistry',
        address: '0x04C0b249740175999E5BF5c9ac1dA92431EF34C5',
        type: 'target',
        category: 'core',
        _note: 'Detached from controller',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'BondingManager',
        address: '0x35Bcf3c30594191d53231E4FF333E8A770453e40',
        type: 'proxy',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'Controller',
        address: '0xD8E8328501E9645d16Cf49539efC04f734606ee4',
        type: 'standalone',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'DelegatorPool',
        address: '0xfdb06109032AD3671a8f14f5f2E78f4B9E81b567',
        type: 'standalone',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'Minter',
        address: '0x4969dcCF5186e1c49411638fc8A2a020Fdab752E',
        type: 'standalone',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'Minter',
        address: '0xc20DE37170B45774e6CD3d2304017fc962f27252',
        type: 'standalone',
        category: 'core',
        version: 'V2',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'RoundsManager',
        address: '0xdd6f56DcC28D3F5f27084381fE8Df634985cc39f',
        type: 'proxy',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'RoundsManager',
        address: '0x92d804Ed49D92438aEA6fe552BD9163aacb7E841',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'ServiceRegistry',
        address: '0xC92d3A360b8f9e083bA64DE15d95Cf8180897431',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'ServiceRegistry',
        address: '0x38093CDca43aeCd7bb474983519A246e93A3b0a7',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
      {
        name: 'TicketBroker',
        address: '0xa8bB618B1520E284046F3dFc448851A1Ff26e41B',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:03.640Z',
      },
    ],
    historical: {
      'BondingManager (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0xe479B9fbA2Cd65f822f451fC8C145c663B995CE6',
          },
          {
            version: 'V2',
            address: '0xC40df4db2f99e7e235780A93B192F1a934f0c45b',
          },
          {
            version: 'V3',
            address: '0x3757DB506ECd9CBE643660C0F5b70db5b321202C',
          },
          {
            version: 'V4',
            address: '0x0f9C425E7374602C20370d3fd263155B4c3bDc91',
          },
          {
            version: 'V5',
            address: '0x3a941e1094B9E33efABB26a9047a8ABb4b257907',
          },
          {
            version: 'V6',
            address: '0x9c9209c9ff6996513b3673d69ee7b36a6c58a8cf',
          },
          {
            version: 'V7',
            address: '0x363cdB9BaE210Ef182c60b5a496139E980330127',
          },
          {
            version: 'V8',
            address: '0x557093B1Ab53412166beAd939f34244170b6525B',
          },
          {
            version: 'V9',
            address: '0x6b397f20DC227B4E23fEc20BBDBe166d0DFFC452',
          },
          {
            version: 'V10',
            address: '0xd1C1F5d44D8F83ca2A05Baf40461e550cFDDecA2',
          },
          {
            version: 'V11',
            address: '0xF62C30242fccd3a46721f155d4d367De3fD5B3b3',
          },
          {
            version: 'V12',
            address: '0x4bA7E7531Ab56bC8d78dB4FDc88D21F621f34BB4',
          },
          {
            version: 'V13',
            address: '0xdA6fe3f332Ae11539b3cF777284Ae70fd3bF2D74',
          },
        ],
      },
      'TicketBroker (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0x7Beb84c52ce96DFd90431FAA97378994a8baa6df',
          },
          {
            version: 'V2',
            address: '0xD906D192e2503Aafd1BC5F5fc4163E842D5B1d6e',
          },
          {
            version: 'V3',
            address: '0xea1b0F6c8D158328a6e3D3F924B86A759F41465c',
          },
        ],
      },
      'BondingVotes (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0x1561fC5F7Efc049476224005DFf38256dccfc509',
          },
          {
            version: 'V2',
            address: '0x68AF80376Bc1CA0C25a83b28e5570E8c7bdD3119',
          },
        ],
      },
      Minter: {
        entries: [
          {
            version: 'V1',
            address: '0x4969dcCF5186e1c49411638fc8A2a020Fdab752E',
          },
        ],
      },
      'L2Migrator (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0x4F59b39e2ea628fe8371BDfd51B063319339c7EE',
          },
        ],
      },
    },
  },
  ethereumMainnet: {
    current: [
      {
        name: 'BridgeMinter',
        address: '0x8dDDB96CF36AC8860f1DE5C7c4698fd499FAB405',
        type: 'standalone',
        category: 'token',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'LivepeerToken',
        address: '0x58b6a8a3302369daec383334672404ee733ab239',
        type: 'standalone',
        category: 'token',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'Governor',
        address: '0xFC3CBed6A3476F7616CC70f078397700136eEBFd',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'MerkleSnapshot',
        address: '0x24ebEd82c681f435E944BEEbFAEEAaE443D08438',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'PollCreator',
        address: '0xBf824EDb6b94D9B52d972d5B25bCc19b4e6E3F3C',
        type: 'standalone',
        category: 'governance',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'L1Escrow',
        address: '0x6A23F4940BD5BA117Da261f98aae51A8BFfa210A',
        type: 'standalone',
        category: 'bridge',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'L1LPTDataCache',
        address: '0x1d24838b35A9c138Ac157A852e19e948aD6323D7',
        type: 'standalone',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'L1LPTGateway',
        address: '0x6142f1C8bBF02E6A6bd074E8d564c9A5420a0676',
        type: 'standalone',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'L1Migrator',
        address: '0x21146B872D3A95d2cF9afeD03eE5a783DaE9A89A',
        type: 'standalone',
        category: 'bridge',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'GenesisManager',
        address: '0x3a9543d4767b2c914ea22fd0b07e17b0901aaebf',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'MerkleMine',
        address: '0x8e306b005773bee6ba6a6e8972bc79d766cc15c8',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'MultiMerkleMine',
        address: '0x182ebf4c80b28efc45ad992ecbb9f730e31e8c7f',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'Refunder',
        address: '0x780c98cbb0cc21d6617c05332bd5cf6f847c71c2',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'SortedDoublyLL',
        address: '0x1a0b2ca69ca2c7f96e2529faa6d63f881655d81a',
        type: 'standalone',
        category: 'utility',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'BondingManager',
        address: '0x511bc4556d823ae99630ae8de28b9b80df90ea2e',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'BondingManager',
        address: '0x5FE3565dB7F1Dd8d6A9E968D45BD2Aee3836a1D4',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'Controller',
        address: '0xf96d54e490317c557a967abfa5d6e33006be69b3',
        type: 'standalone',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'Minter',
        address: '0x505F8c2ee81f1C6fa0D88e918eF0491222E05818',
        type: 'standalone',
        category: 'core',
        isHistorical: false,
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'RoundsManager',
        address: '0x3984fc4ceeef1739135476f625d36d6c35c40dc3',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'RoundsManager',
        address: '0xC89fE48382F8fda6992dC590786A84275bCD1C57',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'ServiceRegistry',
        address: '0x406a112f3218b988c66778fd72fc8467f2601366',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'ServiceRegistry',
        address: '0x72d9dfa25f75a5f2c27b7336e643a559ae6aeb8e',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'TicketBroker',
        address: '0x5b1ce829384eebfa30286f12d1e7a695ca45f5d2',
        type: 'proxy',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
      {
        name: 'TicketBroker',
        address: '0x6F582E2bB19ac31D4B1e6eDD0c2eFEabD700f808',
        type: 'target',
        category: 'core',
        verified: true,
        verifiedAt: '2026-03-26T04:46:18.058Z',
      },
    ],
    historical: {
      LivepeerVerifier: {
        entries: [
          {
            version: 'V1',
            address: '0xf623811b08b45792d0223d77d9c922dae29712ec',
          },
          {
            version: 'V2',
            address: '0xe4be2a35dec0063f9dfccb9b740b1acb7eefefec',
          },
        ],
      },
      Minter: {
        entries: [
          {
            version: 'V1',
            address: '0x8573f2f5a3bd960eee3d998473e50c75cdbe6828',
          },
        ],
      },
      'BondingManager (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0x81eb0b10ff8703905904e4d91cf6aa575d59736f',
          },
          {
            version: 'V2',
            address: '0x5A9512826EAAF1FE4190f89443314E95A515fE24',
          },
          {
            version: 'V3',
            address: '0x633101b3f15f93c5f415830d48e56b9b1f7ba584',
          },
          {
            version: 'V4',
            address: '0x05C03EA0039f2e828A725A82939fc1e90de38B44',
          },
          {
            version: 'V5',
            address: '0xCBAa6eA4886b535FC7ABACe3F3985Ed03b3b80a0',
          },
          {
            version: 'V6',
            address: '0xDC6eE74A18994caD3876a078B6fa4920FD9C507d',
          },
          {
            version: 'V7',
            address: '0x1a6007d1D0583452Bd6f45a4e1a9190B15Fbd7E3',
          },
          {
            version: 'V8',
            address: '0xef5E170b679ddaF5e22ADC10fD23DDdB79E3C0c5',
          },
          {
            version: 'V9',
            address: '0xc8a695155648F18B0cfd6989498B6f8b2c4cc56A',
          },
          {
            version: 'V10',
            address: '0x35F99F326681FE4F38719491be48Ab4950795013',
          },
          {
            version: 'V11',
            address: '0xAC0153a8C5227e43506901a4f3f83FD000c8178f',
          },
          {
            version: 'V12',
            address: '0x246edEBae14b186a67e3d466A485321169a8bcD5',
          },
          {
            version: 'V13',
            address: '0x223398d0BF9cc24960b3886CC481dBf5276EdeD2',
          },
          {
            version: 'V14',
            address: '0x0da7c263eCF5cD3ddba275b9A2D63320E28fD287',
          },
        ],
      },
      'JobsManager (Proxy)': {
        entries: [
          {
            version: 'V1',
            address: '0xbf07ff45f14c9ff0571b9fbdc7e2b62d29931224',
          },
        ],
      },
      'JobsManager (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0x68b463bca7d561118636e9f028ff0f2e8398dd6a',
          },
          {
            version: 'V2',
            address: '0xB620c762dd4bC350602936d7401BB8393Ee6687c',
          },
          {
            version: 'V3',
            address: '0x8eade5eec609572bf53deadb88d36f862ddec517',
          },
        ],
      },
      'RoundsManager (Target)': {
        entries: [
          {
            version: 'V1',
            address: '0xa3aa52ce79e85a21d9ccda705c57e426b160112c',
          },
          {
            version: 'V2',
            address: '0x857d4bf18a80f03d3d11f438825cd3d0aa0d9d68',
          },
        ],
      },
      MerkleProof: {
        entries: [
          {
            version: 'V1',
            address: '0x289ba1701c2f088cf0faf8b3705246331cb8a839',
          },
        ],
      },
    },
  },
  meta: {
    lastUpdated: '2026-03-26T04:46:31.137Z',
    lastVerified: '2026-03-26T04:46:31.137Z',
    sourceRepo: 'livepeer/governor-scripts',
    sourceCommit: '2cb192a',
    verificationSummary: '25/25 Arbitrum, 24/24 Mainnet',
    explorerUrls: {
      arbiscan: 'https://arbiscan.io/address/',
      etherscan: 'https://etherscan.io/address/',
    },
  },
}
